Repository USB-CI3715/nodebb-usb-24-stars, pull requests merged in 2024-11, with the labels that each got.

#83 Creación de funcionalidad de asignación de rol de usuario
  public/language/en-US/register.json
  public/src/client/register.js
  src/user/create.js
Labels: esfuerzo bajo

#84 Creacion de dropdown para seleccion de etiqueta de materia para una pregunta
  nodebb-plugin-composer-question/static/lib/composer.js
Labels: esfuerzo medio

#88 Añadir funcionalidad de obtener las preguntas del usuario
  dump.rdb
  plugins/nodebb-plugin-questions-and-answers/templates/partials/topic-list-bar.tpl
  public/src/app.js
  public/src/questionsDisplay.js
  temp-2661.rdb
Labels: esfuerzo medio

#95 Implementación del Filtro de Búsqueda de Preguntas
  dump.rdb
  plugins/nodebb-plugin-questions-and-answers/templates/partials/topic-list-bar.tpl
  plugins/nodebb-plugin-questions-and-answers/templates/topic.tpl
  public/src/app.js
  public/src/displaySearch.js
Labels: esfuerzo bajo

#98 Registro de carnet de estudiantes
  plugins/nodebb-plugin-questions-and-answers/plugin.json
  plugins/nodebb-plugin-questions-and-answers/templates/register.tpl
  public/language/en-US/register.json
  src/user/create.js
Labels: esfuerzo bajo

#100 Validaciones para el input de ID al registrar un estudiante
  src/user/create.js
Labels: esfuerzo bajo

#101 Visualizacion de rol en el perfil de usuario
  plugins/nodebb-plugin-questions-and-answers/library.js
  plugins/nodebb-plugin-questions-and-answers/plugin.json
Labels: esfuerzo bajo

#103 Span para el carnet de estudiante agregado correctamente a la ventana de perfil de usuario
  plugins/nodebb-plugin-questions-and-answers/library.js
  plugins/nodebb-plugin-questions-and-answers/plugin.json
  plugins/nodebb-plugin-questions-and-answers/templates/partials/account/header.tpl
  plugins/nodebb-plugin-questions-and-answers/templates/register.tpl
Labels: esfuerzo bajo

#106 Cambio en el esquema de la base de datos para incluir los atributos role y studentID
  plugins/nodebb-plugin-questions-and-answers/library.js
  plugins/nodebb-plugin-questions-and-answers/plugin.json
  public/openapi/components/schemas/UserObj.yaml
  public/openapi/components/schemas/UserObject.yaml
  src/user/create.js
  src/user/data.js
Labels: bug

#107 Pruebas para verificaciones del StudentID
  test/user.js
Labels: enhancement
